### ISSUE TITLE
Rename confusing symbols in linker script

### ISSUE THREAD

**Issue by bornaehsani** [bespoke-silicon-group/bsg_replicant#212]
Including bsg_tiles_X/Y --> bsg_tg_dim_x/y
__bsg_x/y --> tile_idx_x/y
__bsg_id --> tile_id

Also need to change bsg_tilegroup_int/load/store into bsg_tile_group_shared_int/load/store

**Comment by drichmond** [comment]
Let's discuss loading programs next week. Can you set up a meeting for Monday afternoon?

**Comment by bornaehsani** [comment]
Sure, who do you want in the meeting?

**Comment by drichmond** [comment]
I this CUDA Specific?

**Comment by bornaehsani** [comment]
Yes the original issue I raised is CUDA specific. But requires long effort to change all parameters in bsg_manycore and is of low priority for now.

**Comment by drichmond** [comment]
Was this solved?

**Comment by bornaehsani** [comment]
No not yet, it's low priority considering the current deadlines.

**Comment by drichmond** [comment]
Let's move this to BSG Manycore?
