### ISSUE TITLE
Add "fence" method to Host API

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_replicant#253]
All the host method should do is wait until the credits return to the maximum value. It can have a timeout as well.

I think this should be used in _exit initially. Others can follow.

**Comment by drichmond** [comment]
Depends on #250

**Comment by tommydcjung** [comment]
how does the host check if the credits return to the max value? does it poll the credit value periodically?

**Comment by tommydcjung** [comment]
alternative is to implement a fence packet which blocks the pipeline until the credit counter returns to max

**Comment by drichmond** [comment]
Yes, it would poll the credit value periodically.

**Comment by drichmond** [comment]
But I’m open to other suggestions

**Comment by tommydcjung** [comment]
I think this should be all handled in hardware. software/host shouldn't have to worry about how many credits are left.

**Comment by drichmond** [comment]
So a fence would be sort of like a request packet - It would go out, and the response wouldn’t be enqueued until the credits were returned

**Comment by tommydcjung** [comment]
host should be able to sent load, store, fence packet. fence blocks all the subsequent packets until the credit counter is fully restored. fence is not actually sent out to the network.

**Comment by tommydcjung** [comment]
after host sends the fence, host should still be able to send other load/store packets. to take advantage of the big fifo..

**Comment by drichmond** [comment]
Yeah, that’s what I meant. The fence would never leave the host interface.

**Comment by drichmond** [comment]
This sounds a bit like multithreading, which we don’t currently support. Is that accurate?

**Comment by tommydcjung** [comment]
when the host program sends load for example, is it blocking or non-blocking? presumably, the host can send out multiple requests and get the response asynchronously

**Comment by drichmond** [comment]
We batch, but it’s blocking. Multiple loads (or stores) can be in flight at the same time, but they’re all from the same method call

**Comment by max-ruttenberg** [comment]
@drichmond addressed in https://github.com/bespoke-silicon-group/bsg_f1/pull/249?

**Comment by drichmond** [comment]
No - there should be an explicit low-level driver method that we can call that blocks until the credits return to maximum.

**Comment by drichmond** [comment]
@tommydcjung and I were debating how this would happen - for example, we could send a special "fence" packet that would cause the host interface to block sending requests until the credits are all returned, and then return the fence packet to the host. Or we could block in software. 

There are benefits and drawbacks to both.

**Comment by drichmond** [comment]
@leonardxiang we should also be able to read remaining credits in your pr

**Comment by taylor-bsg** [comment]
The fence packet is an interesting idea.

M

**Comment by dpetrisko** [comment]
How would this differ from using a fence instruction on the core?

**Comment by drichmond** [comment]
It's a fence issued/triggered by the host?

**Comment by dpetrisko** [comment]
My thought is that sending a fence packet to the core == executing a fence instruction on the core + store to host

**Comment by dpetrisko** [comment]
I guess what you're saying is that this would happen outside normal program execution?

**Comment by drichmond** [comment]
Yeah. In addition - the host could send to DRAM, which may not be observed by the fence issued from the core?

**Comment by taylor-bsg** [comment]
I think what Tommy is talking about is that the Xeon can enqueue a sequence
of loads, stores and fence packets into the FIFO that lives in the FPGA but
is before the manycore network. The Hardware in charge of dequeing from
that FIFO also maintains an outstanding request counter.  When it sees a
fence packet it waits until the counter is zero before dequeuing the fence
packet and proceeding to the next operation. This allows the Xeon to ensure
fence semantics with minimal performance penalty. Since the only way to
loads and stores to the manycore is through that FIFO, we don’t need to
worry about the fence not having its semantics enforced. The Xeon still
maintains link-level synchronization over PCIE with the FIFO to avoid
overflowing it.

M

**Comment by drichmond** [comment]
Yes. However - would a host want to know when that fence packet is dequeued? Or would they issue another packet after the fence (An idempotent read, perhaps)

**Comment by taylor-bsg** [comment]
As long as there is only one pipe for memory requests to get from the host
to the device, the host does not generally need to know when the fence is
dequed for general functionality.  The two exceptions might be teardown
(have all packets completed?) or precision timing. A load after the fence
could be used to verify end-to-end (including the pipe from Xeon to FPGA,
which technically is not tracked by the fence).

**Comment by drichmond** [comment]
Fixed in #503
