### ISSUE TITLE
Need bsg_print_time

### ISSUE THREAD

**Issue by bornaehsani** [bespoke-silicon-group/bsg_replicant#345]
The bsg_print_time macro in the bsg_manycore right now just outputs a dummy value to a specific address. In COSIM we can read the time that is printed with the packet statement, but it doesn't work with F1. We need to implement it perhaps similar to bsg_print_int so it prints out the time on the host interface.

**Comment by drichmond** [comment]
Similar to #186

**Comment by drichmond** [comment]
Does #601 Solve this?

**Comment by bornaehsani** [comment]
Yes I believe so!
