### ISSUE TITLE
Warnings during AFI compilation

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_replicant#471]
We currently see these warnings during Vivado compilation. I'll put these here in case others have time track them down.

`WARNING: [Synth 8-7032] RAM "genblk1[1].mem_reg" have possible Byte Write pattern, however the data width (15) is not multiple of supported byte widths of 8 or 9 .`

Tommy says that this is referring to stat_mem in the Victim Cache (Please correct me if I'm wrong). I believe we've seen this before and we created a hardened Xilinx-specific IP. I consider this issue severe, since it has caused bugs in the past.

```INFO: [Synth 8-5534] Detected attribute (* keep = "true" *) [/mnt/users/spin0/no_backup/drichmond/Research/repositories/git/bsg_bladerunner/bsg_f1/build/src_post_encryption/bsg_fpu_i2f.v:88]
        Parameter width_p bound to: 32 - type: integer 
        Parameter width_p bound to: 32 - type: integer 
        Parameter lg_width_lp bound to: 5 - type: integer 
        Parameter width_p bound to: 32 - type: integer 
        Parameter lo_to_hi_p bound to: 1 - type: integer 
        Parameter width_p bound to: 32 - type: integer 
        Parameter lo_to_hi_p bound to: 1 - type: integer 
        Parameter width_p bound to: 32 - type: integer 
        Parameter xor_p bound to: 0 - type: integer 
        Parameter and_p bound to: 0 - type: integer 
        Parameter or_p bound to: 1 - type: integer 
        Parameter lo_to_hi_p bound to: 1 - type: integer 
        Parameter e_p bound to: 8 - type: integer 
        Parameter m_p bound to: 23 - type: integer 
        Parameter data_width_p bound to: 32 - type: integer 
        Parameter width_p bound to: 38 - type: integer 
        Parameter reset_val_p bound to: 0 - type: integer 
        Parameter harden_p bound to: 0 - type: integer 
        Parameter width_p bound to: 130 - type: integer 
        Parameter x_max_p bound to: 4 - type: integer 
        Parameter y_max_p bound to: 5 - type: integer 
        Parameter nets_p bound to: 1 - type: integer 
WARNING: [Synth 8-5856] 3D RAM reset_i_r_reg  for this pattern/configuration is not supported. This will most likely be implemented in registers
```

Only the last line in the message above is concerning. This is referring to `bsg_fpu_i2f.v`. I don't know the severity of this issue, but since it says "this will most likely be implemented in registers" I consider this warning to be concerning, but not severe. 

```INFO: [Synth 8-6155] done synthesizing module 'bsg_decode' (13#1) [/mnt/users/spin0/no_backup/drichmond/Research/repositories/git/bsg_bladerunner/bsg_f1/build/src_post_encryption/bsg_decode.v:7]
WARNING: [Synth 8-5858] RAM data_li_reg from Abstract Data Type (record/struct) for this pattern/configuration is not supported. This will most likely be implemented in registers
WARNING: [Synth 8-5858] RAM mask_li_reg from Abstract Data Type (record/struct) for this pattern/configuration is not supported. This will most likely be implemented in registers
```

This appears to be a type warning. Like above, it just says that this will be most likely implemented in registers so I'm not greatly concerned.

**Comment by taylor-bsg** [comment]
Do we have post-synthesis regression working with Xilinx? Maybe that is a
reasonable way to catch these kinds of issues?

M

**Comment by drichmond** [comment]
Nope

**Comment by taylor-bsg** [comment]
But Leonard has the design synthesizing for Shortstack right? So we could hook up that netlist to VCS

**Comment by drichmond** [comment]
Theoretically, yes. I've never done that.

**Comment by leonardxiang** [comment]
> We currently see these warnings during Vivado compilation. I'll put these here in case others have time track them down.
> 
> `WARNING: [Synth 8-7032] RAM "genblk1[1].mem_reg" have possible Byte Write pattern, however the data width (15) is not multiple of supported byte widths of 8 or 9 .`
> 
**Yes, I can find the same warning at the synthesis stage of the non-blocking cache design on VU37p. And I double checked the implementation, both state_mem and tag_mem are correctly inferred as distributed ram RAM64X1S.
As is described here
https://github.com/bespoke-silicon-group/basejump_stl/blob/eafa9a41c773530133d6ea9fb405f5809fd7181f/hard/ultrascale_plus/bsg_mem/bsg_mem_1rw_sync_mask_write_bit.v#L2-L12**

> WARNING: [Synth 8-5856] 3D RAM reset_i_r_reg  for this pattern/configuration is not supported. This will most likely be implemented in registers
> 
> Only the last line in the message above is concerning. This is referring to `bsg_fpu_i2f.v`. I don't know the severity of this issue, but since it says "this will most likely be implemented in registers" I consider this warning to be concerning, but not severe.
> 
**Have the same error, tracked one reset_i_r_reg to be the manycore reset input:
Because the tool does not support 3D ram, it is implemented as register at end.
https://github.com/bespoke-silicon-group/bsg_manycore/blob/1efa6ec5e5b084aee677364e1db1b7e48c1ee75a/v/bsg_manycore.v#L161-L163
We can also use (* srl_style = “register” *) to force the tool to infer registers**

> WARNING: [Synth 8-5858] RAM data_li_reg from Abstract Data Type (record/struct) for this pattern/configuration is not supported. This will most likely be implemented in registers
> WARNING: [Synth 8-5858] RAM mask_li_reg from Abstract Data Type (record/struct) for this pattern/configuration is not supported. This will most likely be implemented in registers
> 
> 
> This appears to be a type warning. Like above, it just says that this will be most likely implemented in registers so I'm not greatly concerned.

**Comment by tommydcjung** [comment]
how about we make it like this?
```
  logic [num_tiles_y_p-1:0][num_tiles_x_p-1:0] reset_i_r [reset_depth_p-1:0];
```

**Comment by leonardxiang** [comment]
Not sure, see https://www.xilinx.com/support/documentation/sw_manuals/xilinx2017_1/ug901-vivado-synthesis.pdf P150 for details.

**Comment by taylor-bsg** [comment]
Tommy — don’t do 2D assignments. Not synthesis friendly.


M

**Comment by drichmond** [comment]
BaseJump Style Guide addition? (if not already there)

**Comment by dpetrisko** [comment]
> Tommy — don’t do 2D assignments. Not synthesis friendly.

Can you elaborate here? Do you mean 2d non-blocking assignments i.e. flops?  Because we have Nd arrays of wires all over BP/MC.

**Comment by taylor-bsg** [comment]
This is just based on my neural net somehow generalizing the things I have
tried that have not worked over the years.


wire [4:0][3:0][2:0] a,b;

Good:

a <= b
a[j][k] <=  b[m][n];

Bad:

a[1:0] <= b[3:2];
a[1] <= b[3];

instead, use for loops.

**Comment by drichmond** [comment]
(Commenting so that this issue doesn't die)

**Comment by drichmond** [comment]
The vast majority of these warnings have disappeared with HardFloat. Here are the remaining ones: 

I'm not sure if we can fix this one, or if we want to. It refers to the clog2 function. 
```
WARNING: [Synth 8-6104] Input port 'a' has an internal driver [bsg_bladerunner/bsg_replicant/build/src_post_encryption/HardFloat_localFuncs.vi:44]
WARNING: [Synth 8-6104] Input port 'a' has an internal driver [bsg_bladerunner/bsg_replicant/build/src_post_encryption/HardFloat_localFuncs.vi:45]
```


Filed an issue for this: 
```
WARNING: [Synth 8-2898] ignoring assertion [bsg_bladerunner/bsg_replicant/build/src_post_encryption/bsg_manycore_endpoint_to_fifos.v:155]
```

Filed an issue for this: 
```
WARNING: [Synth 8-87] always_comb on 'endpoint_out_packet_li_reg[payload]' did not result in combinational logic [/bsg_bladerunner/bsg_replicant/build/src_post_encryption/bsg_manycore_endpoint_to_fifos.v:130]
WARNING: [Synth 8-327] inferring latch for variable 'endpoint_out_packet_li_reg[payload]' [bsg_bladerunner/bsg_replicant/build/src_post_encryption/bsg_manycore_endpoint_to_fifos.v:130]
```

Not sure what this is referring to. More investigation is required.
```
WARNING: [Synth 8-3936] Found unconnected internal register 'tx/fifos[3].onefifo.fifo/dff/data_r_reg' and it is trimmed from '32' to '20' bits. [/bsg_bladerunner/bsg_replicant/build/src_post_encryption/bsg_dff_en.v:18]
```

**Comment by drichmond** [comment]
Closing this, will open an issue for the last remaining item
