### ISSUE TITLE
hb_mc_device_init should allow users to initialize less tiles than the whole array

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_replicant#505]
The default behavior should be all the tiles, but if users want their simulation init to be faster, there should be a method to initialize a subset. 

Borna's excellent experiments today demonstrated that this can reduce cosimulation time by 5x for 1x1 tile groups (which I think is substantial)

@mrutt92 Any thoughts on default arguments?

**Comment by mrutt92** [comment]
Not sure. Isn't the dimensionality set by kernel_enqueue?

**Comment by mrutt92** [comment]
I guess program_init() primes the caches on every node. Seems like that could slow things way down if you're only using a few cores.

**Comment by tommydcjung** [comment]
I would suggest for the memory models where we can add $readmemb, create a bit vector file for each bank, and completely bypass host interface. That should be +10x improvement.

**Comment by mrutt92** [comment]
Yeah and that'll probably be addressing the real issue more than fussing with the default behavior of CUDA.

**Comment by drichmond** [comment]
What tommy is suggesting only works for external memory, right?

**Comment by mrutt92** [comment]
No, I think what Tommy is suggesting works for any of the RAMs (I hope).
I'm already working on a solution to DRAM IO which is a similar approach (except I've moved data store into C++ and I'm using memcpy instead of readmemb).

**Comment by drichmond** [comment]
Since we're switching to C++ models for DRAM, that solution sounds reasonable to me. 

For the kernels that this Issue affects, DRAM overhead is small. The code Borna and I worked on earlier took 100 seconds to execute with full array initialization, vs 19 to execute with single tile-initialization.

**Comment by taylor-bsg** [comment]
Maybe we should run the profiler on hb_mc_device_init ?   ;-)

**Comment by drichmond** [comment]
But we know what the issue is - the runtime has to initialize the instruction cache of every single tile. If your program only uses one tile this is a huge overhead.

**Comment by taylor-bsg** [comment]
Initializing the icache is not an inherently slow operation. We should see why it is slow.

**Comment by drichmond** [comment]
It is slow because IO is slow. For every ICache we have to inititialize every entry with program data. That means every tile requires 1K writes. For a 4x4 manycore array, that's 16K 4-byte writes, or 64K of data being uploaded to the device before a program can run. 

Why do people think this is a controversial change? Unlike a backdoor to the device, it isn't introducing any magic. We've demonstrated that there's a 5x speedup and it requires a simple change to the API that will only affect a few users.

**Comment by taylor-bsg** [comment]
Well, there are two levels to it.

First, before we optimize, we should understand why something is slow.
Agreed, we have 16K writes to do. Are we injecting an icache write packet
into the array every cycle, and if not why not? With Leonard’s AXI code, we
should have much more control over the I/O and be able to optimize the
timing?

If we are actually hitting the limit, then, the next step is to have
parallel host interfaces for simulation. We did this in Raw and it was very
helpful for address I/O slowdowns.

Second, this is a very narrow optimization. Why not just run on a 1x1? Then
everything will run faster, not just initialization. On the other hand, we
still want to run large tile arrays and it will still be slow with this
optimization.

M

**Comment by taylor-bsg** [comment]
ps: agree on the general desireability of avoiding magic. :-)

**Comment by drichmond** [comment]
Great suggestions! Thank you for explaining

**Comment by dpetrisko** [comment]
> f we are actually hitting the limit, then, the next step is to have
> parallel host interfaces for simulation. We did this in Raw and it was very
> helpful for address I/O slowdowns.

And to prepare for having multiple host interfaces. For example, a multi-core BlackParrot :)

**Comment by drichmond** [comment]
Closing because there seem to be better solutions. May issue a related PR that reduces duplicated code
