### ISSUE TITLE
Error when compiling library

### ISSUE THREAD

**Issue by vb000** [bespoke-silicon-group/bsg_replicant#611]
I’m seeing this error with latest [replicant](https://github.com/bespoke-silicon-group/bsg_replicant/commit/3e4be5591ff78269047a273e141c9a15e30f2bc0) and [manycore](https://github.com/bespoke-silicon-group/bsg_manycore/commit/748189a22a778eac309d26fb741aa4a4e6e1b7f7):
```
/mnt/users/ssd1/no_backup/bandhav/bsg_bladerunner/bsg_replicant/libraries/bsg_manycore_loader.cpp:669:38: error: 'icache_segidx' may be used uninitialized in this function [-Werror=maybe-uninitialized]
         rc = hb_mc_loader_get_segment(bin, sz, icache_segidx, &icache_phdr, &icache_data);
              ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Just making this a warning with `-Wno-maybe-uninitialized` seems to be working.

**Comment by yodada** [comment]
`make regression` under examples
`make clean` under examples
`make regression` under examples/python

it seems this sequence of actions can produce this problem

**Comment by drichmond** [comment]
I suspect this is introduced by `devtoolset-8`

We should fix this in the code, but it is not occurring when I build the libraries (it is just a warning) and I am not using `devtoolset-8`
