### ISSUE TITLE
Request for BSG Bladerunner ASIC Synthesis and Implementation Report

### ISSUE THREAD

**Issue by vijayholimath** [bespoke-silicon-group/bsg_replicant#631]
@drichmond and the team, may I request you to provide ASIC synthesis and implementation report of BSG Bladerunner? Unfortunately, I don't have Cadence and Synopsys tools.  I am using FPGA version 3.5.2

Many Thanks.

**Comment by taylor-bsg** [comment]
Hi Vijay,

I hope you are well. The numbers (frequency, cores per mm^2) are very
similar to the Celerity chip which is described  off of my webpage.

M

**Comment by vijayholimath** [comment]
Many thanks for the clarification, Michael...:) Yes, I am aware of the paper "The Celerity Open-Source 511-Core RISC-V Tiered Accelerator Fabric" . By the way, we have requirement coming-up to fabricate chip. May I request you to assist us in implementing the chip? Of course, the team/group will be compensated..:)
