### ISSUE TITLE
Bug found when making replicant library for BladeRunner v5

### ISSUE THREAD

**Issue by XingyaoZhang** [bespoke-silicon-group/bsg_replicant#680]
https://github.com/bespoke-silicon-group/bsg_replicant/blob/8e3ede1a48634aeffcbbdecb9c40424ae94d1718/libraries/bsg_manycore_coordinate.h#L186-L189

The error happens when making the replicant library for BladeRunner v5: 
`/mnt/users/ssd2/homes/xingyaoz/research/bsg_bladerunner_vcs_v5/bsg_replicant/libraries/bsg_manycore_coordinate.h: In function ‘hb_mc_coordinate_add’:`
`/mnt/users/ssd2/homes/xingyaoz/research/bsg_bladerunner_vcs_v5/bsg_replicant/libraries/bsg_manycore_coordinate.h:95:34: error: expected expression before ‘{’ token
 #define HB_MC_COORDINATE(xv, yv) {.x = xv, .y = yv}`

The reason is that there needs to be an instance to take the .x and .y assignment, the following code can address the bug:
```
static inline hb_mc_coordinate_t hb_mc_coordinate_add(hb_mc_coordinate_t first, hb_mc_coordinate_t second)
 {
                hb_mc_coordinate_t ret = HB_MC_COORDINATE(first.x+second.x, first.y+second.y);
                return ret;
 }
```

**Comment by drichmond** [comment]
Cool, can you submit a PR if you haven't already?

**Comment by drichmond** [comment]
I'm reading my email from oldest to newest
