### ISSUE TITLE
test_dma fails on the Bigblade-VCS platform

### ISSUE THREAD

**Issue by sripathi-muralitharan** [bespoke-silicon-group/bsg_replicant#726]
On the bigblade branch, the library test, `test_dma` fails. It seems like the manycore platform fails to initialize correctly and receives  the error message show below - 
![Screenshot from 2021-05-06 13-27-48](https://user-images.githubusercontent.com/17497327/117362369-05189780-ae70-11eb-91b7-101e5f274b65.png)

**Comment by drichmond** [comment]
No longer seeing this issue. Closing
