### ISSUE TITLE
How to run dpi-verilator mode 

### ISSUE THREAD

**Issue by Kelin9298** [bespoke-silicon-group/bsg_replicant#758]
Hi,

I followed the Verilator (Beta) setup steps in bladerunner, and then changed the BSG_PLATFORM to 
`BST_PLATFORM ?= dpi-verilator`. And then type `make regression`, but it showed warnings like `BSG MAKE WARN: Couldn't find bsg_cadenv. User must configure CAD Environment.` And also I got `make[3]: *** No rule to make target `exec.log', needed by `regression'.  Stop.` Then the regression stopped with Errors

Can anyone give me a correct way to run dpi-verilator mode ?

**Comment by Kelin9298** [comment]
Also I have a similar problem running with `dpi-vcs` mode. Showing `BSG MAKE WARN: Couldn't find bsg_cadenv. User must configure CAD Environment.` and `BSG MAKE WARN: Using /home/qemudemo/bsg_products/bsg_bladerunner_vcs_test/bsg_bladerunner/bsg_replicant/../aws-fpga as AWS_FPGA_REPO_DIR variable`. And then the regression end with Error.

I found that bsg_cadenv was used in many places. How can I run successfully without having bsg_cadenv? 
I've tried to export VCS_HOME. But still ends with error.

**Comment by drichmond** [comment]
Hi @Kelin9298 

Super excited you're trying to run our project!

Verilator isn't supported at the moment. We're in a transitional phase for bringing back support. #746 updates the README, but it never got merged. 

We're in the middle of some deadlines right now, so I can't give you a hard timeframe for when it will be working again. #752 is the PR that will re-add support. If you track that PR you'll know when it gets merged and is ready to go

**Comment by drichmond** [comment]
As for your second question, bsg_cadenv is the way we manage licenses and tools internally at UW. That repository is not public, so this is merely a warning saying that in the absence of that folder, the user is responsible for setting PATH, VCS_HOME and LM_LICENSE_FILE to run VCS.

This warning would still show up with Verilator, but I suppose we can probably find a clever way to turn it of when running with VCS.

**Comment by drichmond** [comment]
Hi @Kelin9298, verilator support will be merged in the next couple of days. See #752

**Comment by Kelin9298** [comment]
Hi @drichmond, that sounds great. I'm looking forward to the new merge. Thanks.
