### ISSUE TITLE
make: entering an unknown directory

### ISSUE THREAD

**Issue by natewise** [bespoke-silicon-group/bsg_replicant#795]
So I'm running now in a Red Hat 7.4 environment with the pod_X1Y1_ruche_X16Y8_hbm machine, using the Xcelium platform from the _xcelium_ branch, and trying the run the _make regression_ command. I've been able to get most of the SPMD tests to work, but very few of the CUDA examples. Here are the SPMD tests I've had to remove (in _bsg_replicant/examples/spmd/Makefile_):
<img width="293" alt="image" src="https://user-images.githubusercontent.com/32283998/174391402-9fe7b80d-654b-4eb1-be1f-c786c7f446d7.png">
At first, I got an error like "make: entering an unknown directory", but now when I comment out these substitutions and allow the test to run I get something like this for each:
<img width="347" alt="image" src="https://user-images.githubusercontent.com/32283998/174390940-8df930ea-d7da-4c58-9d25-1c4f608703c1.png">
And in _bsg_replicant/examples/cuda/Makefile_, the only tests I could leave uncommented was _test_empty_parallel, test_dma_, and _group_stride_. I also had to comment the _test_loader_ test in _bsg_replicant/examples/python/Makefile_. Any ideas for debugging these tests?

**Comment by drichmond** [comment]
That is... very odd.

@dpetrisko Set up the xcelium platform. Can you weigh in?

**Comment by natewise** [comment]
Dan was actually the one who recommended I open an issue an issue here xD But maybe he'll have some more input if there aren't any other ideas you might have

**Comment by drichmond** [comment]
If @dpetrisko can give me instructions for running it at UW, I'll try it here. I haven't seen this error before, and all those tests run here.

**Comment by dpetrisko** [comment]
I don’t think it has to do with xcelium, as it’s failing before make is even getting to the test directory?

just switching to the xcelium branch and switching the platform to xcelium will reproduce our setup

**Comment by drichmond** [comment]
How are you setting XRUN? (I think I missing some cadenv variable)

**Comment by natewise** [comment]
I had to run _setenv XMSIM xmsim_ and _setenv XRUN xrun_ in my terminal before running _make regression_. Not sure if there's a better way of doing it though

**Comment by drichmond** [comment]
My question was directed toward Dan. There's a standard way at UW that I don't have a branch for yet

**Comment by drichmond** [comment]
Ah, found it. An oddity I'll figure out later

**Comment by drichmond** [comment]
I see two issues, so far. The first is simple, and for @dpetrisko. svdpi.h isn't being included:

```
diff --git a/libraries/platforms/bigblade-xcelium/library.mk b/libraries/platforms/bigblade-xcelium/library.mk
index 89ab8c5e..adafaab2 100644
--- a/libraries/platforms/bigblade-xcelium/library.mk
+++ b/libraries/platforms/bigblade-xcelium/library.mk
@@ -49,6 +49,7 @@ $(PLATFORM_OBJECTS) $(PLATFORM_REGRESSION_OBJECTS): INCLUDES += -I$(LIBRARIES_PA
 $(PLATFORM_OBJECTS) $(PLATFORM_REGRESSION_OBJECTS): INCLUDES += -I$(LIBRARIES_PATH)/platforms/dpi-verilator
 $(PLATFORM_OBJECTS) $(PLATFORM_REGRESSION_OBJECTS): INCLUDES += -I$(BSG_MACHINE_PATH)/notrace/
 $(PLATFORM_OBJECTS) $(PLATFORM_REGRESSION_OBJECTS): INCLUDES += -I$(BSG_PLATFORM_PATH)
+$(PLATFORM_OBJECTS) $(PLATFORM_REGRESSION_OBJECTS): INCLUDES += -I$(XCELIUM_RELEASE)/tools.lnx86/include/
 $(PLATFORM_OBJECTS) $(PLATFORM_REGRESSION_OBJECTS): INCLUDES += -I$(BSG_MANYCORE_DIR)/testbenches/dpi/
 $(PLATFORM_OBJECTS) $(PLATFORM_REGRESSION_OBJECTS): INCLUDES += -I$(BASEJUMP_STL_DIR)/bsg_test/
```

The second is weirder, and I'm not sure it solves your issue but it solves another one I encountered. #786 fixes some outdated link flags. When I rebase the xcelium branch on fix_pod_repl, the issues I was seeing go away.

Neither issue resolves what you described, but I can now run any CUDA test just fine.

**Comment by drichmond** [comment]
You can checkout my changes at `dr-xcelium`

**Comment by dpetrisko** [comment]
Awesome, feel free to push your changes to the xcelium branch itself

**Comment by drichmond** [comment]
I rebased, so it would be a force. That's why I was hesitant

**Comment by dpetrisko** [comment]
The xcelium binary should automatically include svdpi by default (and this did work for me) but this is probably a safer choice. Although XCELIUM_RELEASE isn’t necessarily a standard variable. Maybe we add an error if it’s not defined?

**Comment by dpetrisko** [comment]
I’m not particularly sentimental about git history

**Comment by drichmond** [comment]
Me either, but I don't like force pushing branches that are actively being used by others :)

**Comment by drichmond** [comment]
I just force pushed the xcelium branch after merging #786. I also brought it up to feature parity with VCS.

In other words, this branch should work, along with the force pushed branch from bsg_manycore

**Comment by drichmond** [comment]
I force pushed both `xcelium` branches a couple days ago to bring them up-to-date. You can run `git fetch` and then `git reset --hard origin/xcelium` to collect the changes without recloning.

And yes, you need to change bigblade-vcs to bigblade-xcelium. Our default platform is vcs.

**Comment by drichmond** [comment]
That is probably because we set the variable XCELIUM_RELEASE, to the path of our xcelium installation. You should set that variable, and we'll add a check for it in our makefiles (@dpetrisko)

For example, we set these in a makefile fragment that we include in our projects: 

```
CADENCE = /opt/cadence

# Release dirs                                                                                                                                                                    
XCELIUM_RELEASE = $(CADENCE)/XCELIUM2109

# Bin dirs                                                                                                                                                                        
XCELIUM_BIN   = $(XCELIUM_RELEASE)/tools/xcelium/bin
SIMVISION_BIN = $(XCELIUM_RELEASE)/tools/simvision/bin

export XRUN      = $(XCELIUM_BIN)/xrun
export XMSIM     = $(XCELIUM_BIN)/xmsim
export SIMVISION = $(SIMVISION_BIN)/simvision

```

The line that is silently failing and causing this issue is here. You can see how it is incomplete on the fourth line of the screenshot you posted.

https://github.com/bespoke-silicon-group/bsg_replicant/blob/a24fe8d247eb68a59193731e33b19b25b24b2d14/libraries/platforms/bigblade-xcelium/library.mk#L53

**Comment by dpetrisko** [comment]
Check is added to this PR: https://github.com/bespoke-silicon-group/bsg_replicant/pull/796/files

**Comment by natewise** [comment]
@dpetrisko Do you know what XCELIUM_RELEASE should be for the chamber?

**Comment by drichmond** [comment]
I would assume that it is a parent of whatever `which xrun` returns if xrun is on your path

For example if xrun was on our path: 

XCELIUM_RELEASE=`which xrun`/../../../

**Comment by dpetrisko** [comment]
Yeah I found it offline. That’s a neat trick though, maybe it makes sense to have auto detected defaults like that… but another issue, another PR :)

**Comment by natewise** [comment]
So with these changes, I was able to get the CUDA examples to work in our environment, only with the exception of 1 test, _test_vec_add_parallel_. I've also been going through and testing each of the SPMD tests individually. So far almost all the same ones are failing, with the exception of only a few. Other SPMD tests are failing though that weren't before:
<img width="283" alt="image" src="https://user-images.githubusercontent.com/32283998/175722014-50f2e546-2a22-4169-b9c1-2b51ae284363.png">
The commented lines in the pictures are the tests that are working now. I had to add in _bsg_barrier_ and _bsg_barrier_time_ since these are failing now but weren't before also

**Comment by drichmond** [comment]
What's the issue you see in `test_vec_add_parallel`?

**Comment by natewise** [comment]
<img width="491" alt="image" src="https://user-images.githubusercontent.com/32283998/175748716-cb1bbd68-b93c-4be6-9562-f165b1282567.png">
I forgot that I don't have llvm installed, because I had issues with its setup. I mentioned it to Dan, and he said not to worry about it since most of the examples didn't require it. He recently sent me a potential fix for this though, which could fix this example and probably several of the SPMD one's too.

**Comment by dpetrisko** [comment]
Yeah @drichmond is there a way to force GCC compilation of everything? Does it matter? I thought I remembered the LLVM research being pretty old at this point so I don’t necessarily want to spend time spinning it up

**Comment by drichmond** [comment]
LLVM works fine. I use it all the time.

There's no easy way to force all of them to use GCC, though test_vec_add doesn't require it.

I don't recall SPMD programs using LLVM. Is that why they're failing?

**Comment by natewise** [comment]
There's nothing in the SPMD errors directly mentioning LLVM, just that it's "entering an unknown directory", and also the error I screenshotted in my original post

**Comment by drichmond** [comment]
Can you check the tile group dimensions of those tests?

For example:
https://github.com/bespoke-silicon-group/bsg_manycore/blob/151a51862845edb12832944945a7d99d44a84769/software/spmd/hw_barrier_NxN_test/Makefile#L1

Maybe the tests are asking for a larger tile group than your architecture

**Comment by dpetrisko** [comment]
Sorry, I was unclear. I meant that we weren’t able to compile LLVM on our system (our fault), so ideally we would just use GCC for everything. IIRC, some compiler optimizations depend on LLVM, but presumably all can be compiled using GCC at some performance loss

**Comment by drichmond** [comment]
Yes, nothing depends on LLVM. If a test has LLVM as its compiler we can probably change that.

But my question above still stands. What size architecture are you using?

**Comment by dpetrisko** [comment]
Oh sorry missed the question. We’re doing 16x8 for the purposes of bringing up the regression, then we’ll be doing 16x12 for our system. So I think anything that requires minimum size should be fine — wouldn’t be surprised if we encounter a NPOT error somewhere for the latter case

**Comment by drichmond** [comment]
That's odd then. Are you able to reproduce these errors?

**Comment by natewise** [comment]
So I'm still having some issues installing LLVM despite updating our cmake to version 3: 
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/32283998/176052632-e7015123-0191-4566-ae27-9dd8ef9d3730.png)
I'm not sure whether to keep debugging the LLVM installation or to switch to gcc like you guys were mentioning. Would switching to GCC be a good option?

**Comment by dpetrisko** [comment]
I think this is resolved, someone can reopen if they disagree
