### ISSUE TITLE
"undefined reference to `__errno'" from powf call

### ISSUE THREAD

**Issue by natewise** [bespoke-silicon-group/bsg_replicant#814]
So here is the error I'm currently getting in my CUDA application:
```
/home/jwise/Projects/bsg_bladerunner/bsg_manycore/software/riscv-tools/riscv-install/lib/gcc/riscv32-unknown-elf-dramfs/9.2.0/../../../../riscv32-unknown-elf-dramfs/bin/ld: /home/jwise/Projects/bsg_bladerunner/bsg_manycore/software/riscv-tools/riscv-install/lib/gcc/riscv32-unknown-elf-dramfs/9.2.0/../../../../riscv32-unknown-elf-dramfs/lib/libm.a(lib_a-wf_pow.o): in function `.L8':
wf_pow.c:(.text+0x1d0): undefined reference to `__errno'
/home/jwise/Projects/bsg_bladerunner/bsg_manycore/software/riscv-tools/riscv-install/lib/gcc/riscv32-unknown-elf-dramfs/9.2.0/../../../../riscv32-unknown-elf-dramfs/bin/ld: /home/jwise/Projects/bsg_bladerunner/bsg_manycore/software/riscv-tools/riscv-install/lib/gcc/riscv32-unknown-elf-dramfs/9.2.0/../../../../riscv32-unknown-elf-dramfs/lib/libm.a(lib_a-wf_pow.o): in function `.L84':
wf_pow.c:(.text+0x268): undefined reference to `__errno'
/home/jwise/Projects/bsg_bladerunner/bsg_manycore/software/riscv-tools/riscv-install/lib/gcc/riscv32-unknown-elf-dramfs/9.2.0/../../../../riscv32-unknown-elf-dramfs/bin/ld: /home/jwise/Projects/bsg_bladerunner/bsg_manycore/software/riscv-tools/riscv-install/lib/gcc/riscv32-unknown-elf-dramfs/9.2.0/../../../../riscv32-unknown-elf-dramfs/lib/libm.a(lib_a-wf_pow.o): in function `.L85':
wf_pow.c:(.text+0x330): undefined reference to `__errno'
/home/jwise/Projects/bsg_bladerunner/bsg_manycore/software/riscv-tools/riscv-install/lib/gcc/riscv32-unknown-elf-dramfs/9.2.0/../../../../riscv32-unknown-elf-dramfs/bin/ld: wf_pow.c:(.text+0x360): undefined reference to `__errno'
/home/jwise/Projects/bsg_bladerunner/bsg_manycore/software/riscv-tools/riscv-install/lib/gcc/riscv32-unknown-elf-dramfs/9.2.0/../../../../riscv32-unknown-elf-dramfs/bin/ld: wf_pow.c:(.text+0x374): undefined reference to `__errno'
collect2: error: ld returned 1 exit status
make: *** [/home/jwise/Projects/bsg_bladerunner/bsg_replicant/examples/cuda/riscv.mk:400: kernel.riscv] Error 1
```
I've been able to isolate the issue to a `powf` call like so: `float gain = powf(10.0f, (-att_dB / 20.0f));` where att_dB is some float variable. What was interesting to me was that something like `float gain = powf(10.0f, (-0.0f/ 20.0f));` worked (I checked and att_dB was exactly 0, meaning these should be equivalent statements)

After some searching I came across several articles (such as this one here: https://stackoverflow.com/questions/16802263/cs-pow-doesnt-work-with-a-variable-exponent) that essentially agreed adding the `-lm` flag would fix the issue. I tried manually adding it in several of the relevant CUDA Makefiles until learning the flag was already added to the RISCV_LDFLAGS variable (line 388 of bsg_replicant/examples/cuda/riscv.mk). The error is unfortunately still occurring regardless...

Many of these articles complained about an issue like "undefined reference to 'pow'" rather than "undefined reference to `__errno'" like my own. I'm guessing the reason this is unresolved has to do with this difference, but I'm not sure why the linker is having trouble linking to the errno library (adding an include to "errno.h" didn't work either). I would appreciate any insights you guys might be able to give that might resolve this. Thanks!

**Comment by dpetrisko** [comment]
https://community.st.com/s/question/0D50X00009Xkf1KSAR/linker-problem-undefined-reference-to-errno

https://stackoverflow.com/questions/56550457/what-are-the-possible-side-effects-of-using-gccs-fno-math-errno

-f-no-math-errno?

https://github.com/riscv-collab/riscv-gnu-toolchain/issues/929

There are also the -lc -lm -lc ordering hacks suggested here

**Comment by dpetrisko** [comment]
This isn't a bsg_replicant specific question though, you might have better luck on the riscv sw-dev mailing list: https://groups.google.com/a/groups.riscv.org/g/sw-dev

**Comment by natewise** [comment]
After following that first community.st.com link, I tried commenting out `RISCV_LDFLAGS += -nostdlib` (line 383 of cuda/riscv.mk for me)... and it worked! Thank you Dan, I'll close this issue
