### ISSUE TITLE
VCS option "-ntb_opts tb_timescale=1ps/1ps" doesn't appear to work in vcs/U-2023.03-SP2-8

### ISSUE THREAD

**Issue by tajayi-hx** [bespoke-silicon-group/bsg_replicant#830]
As part of the vcs compile options, when "-ntb_opts tb_timescale=1ps/1ps" is specified, I get the following error

```
Error-[SFCOR] Source file cannot be opened
  Source file "tb_timescale=1ps/1ps" cannot be opened for reading due to 'No 
  such file or directory'.
  Please fix above issue and compile again.
```

https://github.com/bespoke-silicon-group/bsg_replicant/blob/d91d1e9df979a62b46d14edd2e03393360810351/libraries/platforms/bigblade-vcs/link.mk#L63C1-L64C1

Removing that option allows the simulation to proceed but I am unsure what the impact is

**Comment by dpetrisko** [comment]
Hi thanks. I think it is a VCS-MX option, and your change not have any impact on functionality

**Comment by tajayi-hx** [comment]
Thanks. World record response time here ;)
Should I plan to maintain a local patch or do you anticipate it being updated?

**Comment by dpetrisko** [comment]
:) 

For this repo, we only maintain the options for our specific tools. I’ll check if your option works for us and update if so, keep it local if not
